[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
startCommand = "bun --bun server.ts"
preDeployCommand = "bun run db:migrate:prod"

[variables]
NODE_ENV = "production"
BETTER_AUTH_URL = "https://rdw.pdcd.net"
